# Welcome to Impatient-Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: Adventures in ASL
email: adventuresinasl@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Adventures in ASL (American Sign Language) is an after school program that helps kids learn sign language and deaf culture.
# twitter_username: 
# github_username:  mikki4

# Build settings
markdown: kramdown

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
